= Proof Of Concept - Integrate Bespoke.js and Demoit
:uri-bespoke: http://markdalgleish.com/projects/bespoke.js
:uri-node: https://nodejs.org
:uri-nvm: https://github.com/creationix/nvm
:uri-ruby: https://www.ruby-lang.org
:uri-rvm: https://rvm.io

== View slides locally

First, ensure you have the following installed:

. {uri-node}[Node.js] >= 4.2 footnote:[You're strongly encouraged to use {uri-nvm}[nvm] to manage Node.]

 $ nvm install stable && nvm use stable

. {uri-ruby}[Ruby >= 2] footnote:[You're strongly encouraged to use {uri-rvm}[RVM] to manage Ruby.]

 $ rvm install ruby --latest

Then build and serve the presentation!

 $ make serve-slides

You can view the presentation in your browser at the URL displayed in the console.

  $ make show-slides

Use the kbd:[<-] and kbd:[->] arrows to navigate the slides.
You can use kbd:[<space>] and kbd:[Shift+<space>] to navigate as well.
Most presentation clickers are compatible with these key bindings.

To build the presentation without starting the preview server, use:

 $ make

In either case, the files are built into the [.path]_dist_ directory.
You can view the slides outside of the local preview server by navigating to [.path]_dist/index.html_ in your browser.

== kbd:[o] -- Slide Overview Mode

This presentation comes with a built-in slide overview mode.
To activate it, simply visit the presentation in your browser and press kbd:[o].
The slides will be rearranged in a grid that you can scroll or navigate with the keyboard.
Press enter to select the highlighted slide and return to presentation mode.

== kbd:[F11] -- Full Screen Mode

This presentation will automatically scale to fit an entire 16:9 screen.
Simply activate full screen mode in your browser by pressing kbd:[F11].

== Customizing the Port

By default, the preview server runs on port 8088.
To change this default, you can assign a different number to the PORT environment variable:

 $ PORT=9000 make serve-slides

